name: oudedetai
base: core24
version: v4.0.0-beta.4
summary: Install and maintain FaithLife's Logos Bible (Verbum) Software.
description: |
  This repository contains a Python program for installing and maintaining
  FaithLife's Logos Bible (Verbum) Software on Linux.

  This program is created and maintained by the FaithLife Community and is
  licensed under the MIT License.
grade: stable
confinement: strict
environment:
  CONFIG_FILE: ${SNAP_USER_COMMON}/${SNAPCRAFT_PROJECT_NAME}.json

apps:
  oudedetai:
    command: bin/run.sh

parts:
  run:
    source: ./snap
    plugin: dump
    organize:
      'run.sh': bin
      'default-config.json': ${CRAFT_PRIME}/etc

  # wine:
  #   source: 

  oudedetai:
    # source: https://github.com/FaithLife-Community/LogosLinuxInstaller/archive/refs/tags/${SNAPCRAFT_PROJECT_VERSION}.tar.gz
    source: https://github.com/FaithLife-Community/LogosLinuxInstaller.git  # just for testing
    plugin: python
    