name: oudedetai
base: core24
version: v4.0.0-beta.5
summary: Install and maintain FaithLife's Logos Bible (Verbum) Software.
description: |
  This repository contains a Python program for installing and maintaining
  FaithLife's Logos Bible (Verbum) Software on Linux.

  This program is created and maintained by the FaithLife Community and is
  licensed under the MIT License.
grade: stable
confinement: strict
environment:
  CONFIG_FILE: ${SNAP_USER_COMMON}/${SNAPCRAFT_PROJECT_NAME}.json
  PYTHON_SITE_PACKAGES_PATH: $SNAP/lib/python3.12/site-packages
  PYTHON_APT_PACKAGES_PATH: $SNAP/usr/lib/python3.12
  PYTHON_LIB_DYNLOAD_PATH: $SNAP/usr/lib/python3.12/lib-dynload
  TCL_LIBRARY: $SNAP/usr/share/tcltk/tcl8.6
  TK_LIBRARY: $SNAP/usr/share/tcltk/tk8.6
  PYTHONPATH: $PYTHON_SITE_PACKAGES_PATH:$PYTHON_APT_PACKAGES_PATH:$PYTHON_LIB_DYNLOAD_PATH:$TCL_LIBRARY:$TK_LIBRARY


apps:
  oudedetai:
    command: bin/run.sh

parts:
  bin:
    source: ./snap/bin
    plugin: dump
    organize:
      run.sh: bin/

  etc:
    source: ./snap/etc
    plugin: dump
    organize:
      oudedetai.json: etc/oudedetai.json

  icu:
    source: https://github.com/FaithLife-Community/icu/releases/download/72.1-custom%2B4/icu-win.tar.gz
    plugin: dump
    organize:
      '*': $SNAP_USER_COMMON

  wine:
    source: squashfs-root/  # "Failed to pull source" when URL is given here
    plugin: dump
    source-type: local
    build-packages:
      - wget
    override-pull: |
      file=wine-devel_9.19-x86_64.AppImage
      wget -q https://github.com/FaithLife-Community/wine-appimages/releases/download/9.19-devel/$file
      if [[ ! -r $file ]]; then
        exit 1
      fi
      chmod +x "$file"
      ./*.AppImage --appimage-extract >/dev/null
      if [[ ! -d squashfs-root ]]; then
        exit 1
      fi
      rm -f *.AppImage
      craftctl default
    # override-build: |
    #   cp -r ./* .
    prime:
      - -AppRun*
      - -.bundle.yml
      - -.DirIcon
      - -*.desktop
      - -*.svg
      - -winedata
      - -wrapper

  oudedetai:
    # source: https://github.com/FaithLife-Community/LogosLinuxInstaller/archive/refs/tags/${SNAPCRAFT_PROJECT_VERSION}.tar.gz
    source: https://github.com/FaithLife-Community/LogosLinuxInstaller.git  # just for testing
    plugin: python

  tk:
    plugin: nil
    stage-packages:
      - python3-tk
    