name: oudedetai
base: core24
version: v4.0.0-beta.5
summary: Install and maintain FaithLife's Logos Bible (Verbum) Software.
description: |
  This repository contains a Python program for installing and maintaining
  FaithLife's Logos Bible (Verbum) Software on Linux.

  This program is created and maintained by the FaithLife Community and is
  licensed under the MIT License.
grade: stable
confinement: strict

platforms:
  amd64:

environment:
  CONFIG_FILE: ${SNAP_USER_COMMON}/${SNAPCRAFT_PROJECT_NAME}.json
  PYTHON_SITE_PACKAGES_PATH: $SNAP/lib/python3.12/site-packages
  PYTHON_APT_PACKAGES_PATH: $SNAP/usr/lib/python3.12
  PYTHON_LIB_DYNLOAD_PATH: $SNAP/usr/lib/python3.12/lib-dynload
  TCL_LIBRARY: $SNAP/usr/share/tcltk/tcl8.6
  TK_LIBRARY: $SNAP/usr/share/tcltk/tk8.6
  PYTHONPATH: $PYTHON_SITE_PACKAGES_PATH:$PYTHON_APT_PACKAGES_PATH:$PYTHON_LIB_DYNLOAD_PATH:$TCL_LIBRARY:$TK_LIBRARY:$PYTHONPATH

apps:
  oudedetai:
    extensions: [gnome]
    command: bin/run.sh
    plugs: &allplugs
      - audio-playback
      - home
      - network
      - opengl
      - removable-media

parts:
  bin:
    source: ./snap/bin
    plugin: dump
    organize:
      run.sh: bin/run.sh

  etc:
    source: ./snap/etc
    plugin: dump
    organize:
      oudedetai.json: etc/oudedetai.json

  icu:
    source: https://github.com/FaithLife-Community/icu/releases/download/72.1-custom%2B4/icu-win.tar.gz
    plugin: dump
    organize:
      '*': etc/

  wine:
    source: https://gitlab.winehq.org/wine/wine.git
    source-tag: wine-9.19
    source-depth: 1
    plugin: autotools
    autotools-configure-parameters:
      - --enable-win64
      - --without-ldap
      - --without-oss
      - --disable-winemenubuilder
      - --disable-win16
      - --disable-tests
      - --enable-archs=i386,x86_64
      - --prefix=/opt/wine-devel

  # wine-appimage:
  #   source: .  # "Failed to pull source" when URL is given here
  #   plugin: dump
  #   source-type: local
  #   build-packages:
  #     - wget
  #   override-pull: |
  #     file=wine-devel_9.19-x86_64.AppImage
  #     wget -q https://github.com/FaithLife-Community/wine-appimages/releases/download/9.19-devel/$file
  #     if [[ ! -r $file ]]; then
  #       exit 1
  #     fi
  #     chmod +x $file
  #     ./$file --appimage-extract >/dev/null
  #     if [[ ! -d squashfs-root ]]; then
  #       exit 1
  #     fi
  #     rm -f $file
  #     # Fix file permissions.
  #     chmod -R go+rX .  # https://forum.snapcraft.io/t/openaudible-bounty/16835/5
  #   stage:
  #     - -AppRun*
  #     - -.bundle.yml
  #     - -.DirIcon
  #     - -*.desktop
  #     - -*.svg
  #     - -winedata
  #     - -wrapper
  #   organize:
  #     'squashfs-root/*': .
  #   # stage-packages:  # when pkg-config runs it can lead to OOM error on my VPS
  #   #   - libcapi20-dev  # libcapi20.so.3
  #   #   - libgphoto2-dev  # libgphoto2.so.6, libgphoto2_port.so.12, 
  #   #   - ocl-icd-opencl-dev  # libOpenCL.so.1
  #   #   - libsane-dev  # libsane.so.1
  #   #   - libusb-1.0-0-dev  # libusb-1.0.so.0

  oudedetai:
    ## just for testing
    source: https://github.com/FaithLife-Community/LogosLinuxInstaller.git
    source-branch: snap-pkg
    ##
    # source: https://github.com/FaithLife-Community/LogosLinuxInstaller/archive/refs/tags/${SNAPCRAFT_PROJECT_VERSION}.tar.gz
    plugin: python
    stage:
      - -lib64  # only a symlink to lib, which collides with lib64 in wine part

  cleanup:
    plugin: nil
    stage-packages:
      - libncurses6
      - libncursesw6
      # - libproxy1v5  # doesn't fix libpxbackend-1.0.so: cannot open shared object file: No such file or directory
      # - glib-networking  # doesn't fix Failed to load module: /home/nate/snap/oudedetai/common/.cache/gio-modules/libgiolibproxy.so
      - python3-tk
    override-prime: |
      echo '<TODO>'
      craftctl default

# Reported unused libs:
# lib/x86_64-linux-gnu/libapprun_hooks.so
# lib/x86_64-linux-gnu/libulockmgr.so.1.0.1
# opt/glibc/lib/x86_64-linux-gnu/libBrokenLocale-2.31.so
# opt/glibc/lib/x86_64-linux-gnu/libSegFault.so
# opt/glibc/lib/x86_64-linux-gnu/libanl-2.31.so
# opt/glibc/lib/x86_64-linux-gnu/libc-2.31.so
# opt/glibc/lib/x86_64-linux-gnu/libcrypt.so.1.1.0
# opt/glibc/lib/x86_64-linux-gnu/libdl-2.31.so
# opt/glibc/lib/x86_64-linux-gnu/libgcc_s.so.1
# opt/glibc/lib/x86_64-linux-gnu/libm-2.31.so
# opt/glibc/lib/x86_64-linux-gnu/libmemusage.so
# opt/glibc/lib/x86_64-linux-gnu/libmvec-2.31.so
# opt/glibc/lib/x86_64-linux-gnu/libnsl-2.31.so
# opt/glibc/lib/x86_64-linux-gnu/libnss_compat-2.31.so
# opt/glibc/lib/x86_64-linux-gnu/libnss_dns-2.31.so
# opt/glibc/lib/x86_64-linux-gnu/libnss_files-2.31.so
# opt/glibc/lib/x86_64-linux-gnu/libnss_hesiod-2.31.so
# opt/glibc/lib/x86_64-linux-gnu/libnss_nis-2.31.so
# opt/glibc/lib/x86_64-linux-gnu/libnss_nisplus-2.31.so
# opt/glibc/lib/x86_64-linux-gnu/libpcprofile.so
# opt/glibc/lib/x86_64-linux-gnu/libpthread-2.31.so
# opt/glibc/lib/x86_64-linux-gnu/libresolv-2.31.so
# opt/glibc/lib/x86_64-linux-gnu/librt-2.31.so
# opt/glibc/lib/x86_64-linux-gnu/libthread_db-1.0.so
# opt/glibc/lib/x86_64-linux-gnu/libutil-2.31.so
# opt/glibstdcpp/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.28
# usr/lib/libBLTlite.2.5.so.8.6
# usr/lib/x86_64-linux-gnu/libform.so.6.4
# usr/lib/x86_64-linux-gnu/libmenu.so.6.4
# usr/lib/x86_64-linux-gnu/libpanel.so.6.4
# usr/lib/x86_64-linux-gnu/libtic.so.6.2
