name: oudedetai
base: core24
adopt-info: oudedetai
summary: Install and maintain FaithLife's Logos Bible (Verbum) Software.
description: |
  This repository contains a Python program for installing and maintaining
  FaithLife's Logos Bible (Verbum) Software on Linux.

  This program is created and maintained by the FaithLife Community and is
  licensed under the MIT License.
grade: stable
confinement: strict

platforms:
  amd64:

environment:
  # Define config variables.
  # FLPRODUCT: Logos
  # TARGET_RELEASE_VERSION: "39.1.0.0006"
  TARGETVERSION: "10"
  INSTALLDIR: "$SNAP_USER_COMMON"
  WINE_EXE: "$SNAP/bin/wine64"
  # Define runtime variables.
  # https://forum.snapcraft.io/t/modulenotfounderror-no-module-named-tkinter/28707/5?u=n8marti
  TCL_LIBRARY: $SNAP/usr/share/tcltk/tcl8.6
  TK_LIBRARY: $SNAP/usr/share/tcltk/tk8.6
  TCLLIBPATH: $SNAP/usr/lib/tcltk/$CRAFT_ARCH_TRIPLET_BUILD_FOR/tk8.6
  PYTHON_SITE_PKGS: $SNAP/lib/python3.12/site-packages
  PYTHON_APT_PKGS: $SNAP/usr/lib/python3.12
  PYTHON_LIB_DYNLD: $SNAP/usr/lib/python3.12/lib-dynload
  PYTHONPATH: $PYTHON_SITE_PKGS:$PYTHON_APT_PKGS:$PYTHON_LIB_DYNLD #:$TCL_LIBRARY:$TK_LIBRARY
  # https://forum.snapcraft.io/t/libpxbackend-1-0-so-cannot-open-shared-object-file-no-such-file-or-directory/44263/2
  # To avoid "ImportError: libBLT.2.5.so.8.6: cannot open shared object file: No such file or directory"
  # TCLTK_LIB: $SNAP/usr/lib/tcltk/$CRAFT_ARCH_TRIPLET_BUILD_FOR/tk8.6
  # BLT_LIB: $SNAP/usr/lib/blt2.5
  LD_LIBRARY_PATH: $SNAP/usr/lib:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR # :$TCLTK_LIB:$BLT_LIB:$TK_LIB

apps:
  oudedetai:
    extensions: [gnome]
    # command: bin/run.sh
    command: bin/oudedetai
    plugs: &allplugs
      - audio-playback
      - home
      - network
      - opengl
      - removable-media

parts:
  # bin:
  #   source: ./snap/bin
  #   plugin: dump
  #   organize:
  #     run.sh: bin/run.sh
  #   stage-packages:
  #     - jq

  assets:
    source: ./ou_dedetai/assets
    plugin: dump
    organize:
      '*': assets/

  img:
    source: ./ou_dedetai/img
    plugin: dump
    organize:
      '*': img/

  # wine-apt:  # installs most recent devel version
  #   plugin: nil
  #   build-packages: [wget]
  #   override-stage: |
  #     dpkg --add-architecture i386
  #     mkdir -pm755 /etc/apt/keyrings
  #     wget -qO /etc/apt/keyrings/winehq-archive.key https://dl.winehq.org/wine-builds/winehq.key
  #     wget -qNP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/noble/winehq-noble.sources
  #     apt-get update
  #     apt-get -y install --install-recommends winehq-devel
  #     craftctl default

  wine-custom:
    source: https://github.com/sil-car/wine-builds/releases/download/wine_10.0/wine_10.0+24.04.tar.xz
    plugin: dump
    organize:
      'wine_*/bin': bin
      'wine_*/lib': lib
      'wine_*/share': share
    stage-packages:
      - libavcodec60
      - libavformat60
      - libavutil58
      - libusb-1.0-0
      - libxkbregistry0

  oudedetai:
    source: https://github.com/FaithLife-Community/LogosLinuxInstaller.git
    # FIXME: just for testing
    source-branch: snap-pkg
    plugin: python
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tag)
    stage-packages:
      - libncurses6
      - libncursesw6
      - python3-tk

  cleanup:
    after:
      - wine-custom
      - oudedetai
    plugin: nil
    override-prime: |
      rm -f lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libicudata.so*
      rm -f usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libicuio.so*
      rm -f usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libicutest.so*
      rm -f usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libicutu.so*
