name: Auto-build & release to test-builds repo
on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/build-branch.yml
    with:
      branch: main

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: ${{ needs.build.outputs.bin_name }}
    - name: Run shell tasks
      run: |
        echo "DATE=$(date +%Y%m%d)" >> $GITHUB_ENV
        find -name oudedetai -type f -exec chmod +x {} \;
    - name: Upload release to test repo
      uses: softprops/action-gh-release@v1
      with:
        # tag_name: main-${{ env.DATE }}-${{ needs.build.outputs.sha_short }}
        tag_name: main-latest
        prerelease: true
        files: ${{ needs.build.outputs.bin_name }}
        repository: FaithLife-Community/test-builds
        token: ${{ secrets.N8MARTI_ACCESS_TOKEN }}
        
