name: Build & upload artifact

on:
  #schedule:
  #  - cron: '0 4,16 * * *'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-branch.yml
    with:
      branch: ${{ inputs.branch }}

  release:
    runs-on: ubuntu-latest
    needs: build
    environment: build
    steps:
    - uses: actions/upload-artifact@v4
      with:
        name: LogosLinuxInstaller
        path: dist/LogosLinuxInstaller
        compression-level: 0
