name: Build & release

on:
  #schedule:
  #  - cron: '0 4,16 * * *'
  workflow_dispatch:
    inputs:
      tag:
        description: "Enter the tag/version number (e.g. 'v4.0.0alpha'):"
        required: true
        type: string
      prerelease:
        description: "Is this a pre-release?"
        required: true
        type: boolean

jobs:
  build:
    uses: ./.github/workflows/build-branch.yml
    with:
      branch: main

  release:
    runs-on: ubuntu-latest
    needs: build
    environment: build
    steps:
    - name: release
      uses: SimWinSports/sw-create-release@v1.0.0
      id: create_release
      with:
        release_branch: main/${{ inputs.tag }}
        prerelease: ${{ inputs.prerelease }}
        tag: ${{ inputs.tag }}
    - name: upload
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ inputs.tag }}
        files: ${{ needs.build.outputs.bin_path }}
        token: ${{ secrets.GITHUB_TOKEN }}
