name: Build & release to test-builds repo
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "branch-name"
        required: true
        type: string
      tag:
        description: "tag-name"
        required: true
        type: string

jobs:
  build:
    uses: ./.github/workflows/build-branch.yml
    with:
      branch: ${{ inputs.branch }}

  release:
    runs-on: ubuntu-latest
    needs: build
    environment: build
    permissions:
      contents: write
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: ${{ needs.build.outputs.bin_name }}
    - name: Upload release to test repo
      uses: softprops/action-gh-release@v0.1.15
      with:
        tag_name: ${{ inputs.tag }}
        files: ${{ needs.build.outputs.bin_name }}
        repository: FaithLife-Community/test-builds
        token: ${{ secrets.ACCESS_TOKEN }}
        
