name: Build & release

on:
  #schedule:
  #  - cron: '0 4,16 * * *'
  workflow_dispatch:
    inputs:
      tag:
        description: "Enter the version string (e.g. 'v4.0.0alpha'):"
        required: true
        type: string
      prerelease:
        description: "Check if pre-release"
        required: true
        type: boolean

jobs:
  build:
    uses: ./.github/workflows/build-branch.yml
    with:
      branch: main

  release:
    runs-on: ubuntu-latest
    needs: build
    environment: build
    permissions:
      contents: write
    steps:
    - name: release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ inputs.tag }}
        prerelease: ${{ inputs.prerelease }}
        files: ${{ needs.build.outputs.bin_path }}
