name: Build with PyInstaller
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "branch-name"
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-20.04
    environment: build
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch }}

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: pip

    - name: Install dependencies
      run: |
        # apt-get install python3-tk
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build with pyinstaller
      run: |
        pyinstaller LogosLinuxInstaller.spec --clean
